### ISSUE TITLE
Add more documentation.

### ISSUE THREAD

**Issue by fakeronan2** [SpookyDervish/PyOS#2]
The lack of documentation makes it very hard to find out the steps to install.

**Comment by SpookyDervish** [comment]
Hey @fakeronan2,

thanks for your feedback. The installation of this is mainly downloading the modules needed. I'll add an install command in a BIOS kind of system in the future.

Thanks,
Spooky.

**Comment by fakeronan2** [comment]
I am closing this as it is essentally a duplicate of pull request 1.

**Comment by Voxelstice** [comment]
technically its fine if the pull request was created after this
